### ISSUE TITLE
Can't open the Giraffe.exe

### ISSUE THREAD

**Issue by 15395167921** [Chimaco37/Maize-Phenotyping#2]
<img width="313" alt="微信图片_20240805150216" src="https://github.com/user-attachments/assets/35ad14ff-fab6-44a8-97a4-c655da44df46">
when i try to open the Giraffe.exe, it looks like something going wrong. How can i fix the problem? Thanks!

**Comment by Chimaco37** [comment]
> <img alt="微信图片_20240805150216" width="313" src="https://private-user-images.githubusercontent.com/113825093/355000653-35ad14ff-fab6-44a8-97a4-c655da44df46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5OTMyMTYsIm5iZiI6MTcyMjk5MjkxNiwicGF0aCI6Ii8xMTM4MjUwOTMvMzU1MDAwNjUzLTM1YWQxNGZmLWZhYjYtNDRhOC05N2E0LWM2NTVkYTQ0ZGY0Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwN1QwMTA4MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOWJmMjQ3ZDU0OTQyYjQ0YjZiNjBiZmE2ZmNlMDkwNjZiYjIyYmE0MjYzZjBmYzcxNGM2OGE2ZDliY2FmODFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2uLICpQF1gbHMv4DpAoj-AowjaDewkuBX-9LAq0LN_Q"> when i try to open the Giraffe.exe, it looks like something going wrong. How can i fix the problem? Thanks!

Thank you for the reminder, I didn't correctly package the logo file into the exe file and will fix it later.
